all:
  hosts:                                
    server1:
      ansible_host: 172.31.24.146
      ansible_user: ec2-user
      ansible_ssh_private_key_file: temp.pem
    server2:
      ansible_host: 172.31.17.232
      ansible_user: ubuntu
      ansible_ssh_private_key_file: temp.pem
    server3:
      ansible_host: 172.31.20.228    
      ansible_user: ec2-user
      ansible_ssh_private_key_file: temp.pem
